// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqGabmoGKq3dKf_5WAvXOdCPXb6PESD3U',
    appId: '1:270698623484:web:f1138b7caf338ac77b0279',
    messagingSenderId: '270698623484',
    projectId: 'automated-attendance-sys-9fc6b',
    authDomain: 'automated-attendance-sys-9fc6b.firebaseapp.com',
    storageBucket: 'automated-attendance-sys-9fc6b.firebasestorage.app',
    measurementId: 'G-776EXP7740',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARDUAxm1_y5rtdZ7ubsbYJ8tRmnJbfJ-4',
    appId: '1:270698623484:android:5eca954a44a925777b0279',
    messagingSenderId: '270698623484',
    projectId: 'automated-attendance-sys-9fc6b',
    storageBucket: 'automated-attendance-sys-9fc6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyDek9jteP7GUDydFAS6i3ZJEnVlA7G7o',
    appId: '1:270698623484:ios:e297e02d88345fac7b0279',
    messagingSenderId: '270698623484',
    projectId: 'automated-attendance-sys-9fc6b',
    storageBucket: 'automated-attendance-sys-9fc6b.firebasestorage.app',
    iosBundleId: 'com.example.automatedAttendanceSystem',
  );
}
